# The URL the site will be built for
base_url = "https://terragrams.com"

title = "Terragrams"
# Below is used as the podcast show description — max 4000 characters
description = "Terragrams is a podcast series that provides a wide portal into landscape architecture and the lives and thoughts of the professionals who shape it. It ran from 2006 to 2011 and is being re-edited & re-broadcast in 2019."
# The default language, used in RSS
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_rss = true

[extra]
# Put all your custom variables here
debug = false
author = "Craig Verzone"
author_email = "TODO"
itunes_id = "TODO"
summary = "Terragrams is a wide portal into landscape architecture and the professionals who shape it" # iTunes super brief description
keywords = "landscape architecture,landscape,architecture,design,sustainability"
itunes_category = "Arts"
itunes_subcategory = "Design"
itunes_type = "episodic"
explicit = "no"
location = "Vevey, Switzerland"
frequency = "Weekly"
show_art_path = "/episodes/Main Art.png" # Show thumbnail/art
