[[chapters]]
image = "1.jpg"
time = "0:37"
title = "Introducing Julie and D.I.R.T. Studio"
credit = "D.I.R.T. Studio"
size = 3

[[chapters]]
image = "2.jpeg"
time = "7:03"
title = "Mined Sites and Contemporary Art"
credit = "Dallas Museum of Art, Robert Smithson, Mirror Displacement on Compost Heap, 1969"
link = "https://collections.dma.org/artwork/5324897"
size = 4

[[chapters]]
image = "3.jpg"
time = "7:03"
title = "Environmental Art & Ancient Landscapes"
credit = "D H Lawrence, Etruscan Places, Entrance to the Chamber Tombs"
link = "http://gutenberg.net.au/ebooks09/0900381h.html"
size = 4

[[chapters]]
time = "10:05"
title = "Teaching and D.I.R.T.'s Future"
size = 2

[[chapters]]
image = "5.jpg"
time = "20:13"
title = "Philadelphia Navy Yard Project"
credit = "Landezine, Philadelphia Navy Yard"
link = "http://landezine.com/index.php/2014/10/urban-outfitters-headquarters-at-the-philadelphia-navy-yard-by-d-i-r-t-studio/"
size = 5

[[chapters]]
time = "24:05"
image = "6.jpg"
title = "Reuse and Barnie Rubble"
credit = "Landezine, Philadelphia Navy Yard"
link = "http://landezine.com/index.php/2014/10/urban-outfitters-headquarters-at-the-philadelphia-navy-yard-by-d-i-r-t-studio/"
size = 5
